from agents import build_search_agent, build_reader_agent, writer_chain, critic_chain

# creating base function for the pipeline
def run_research_pipeline(topic: str) -> dict:

    # here state is a dictionary that will hold the state of the pipeline at each step. we will use this state to pass the data from one step to another. we will also use this state to store the final output of the pipeline.
    state = {}

    # step 1: search the web for recent data about the topic

    print("\n" + "=" * 50)
    print("Step 1: Search Agent is working...")
    print("=" * 50)
    
    search_agent = build_search_agent()
    search_result = search_agent.invoke({
        "input": f"find recent, reliable and detailed information about: {topic}"
    })

    # here we using the above created state
    # this line is used to store the search result in the state dictionary. we are storing the last message content of the search result in the state dictionary with the key "search_result". this will be used in the next step to pass the search result to the reader agent.
    
    # Executing the search tool automatically if the model calls it
    if search_result.tool_calls:
        tool_call = search_result.tool_calls[0]
        from tools import web_search
        state["search_result"] = web_search.invoke(tool_call["args"]["query"])
    else:
        state["search_result"] = search_result.content

    print("\n search result", state["search_result"][:800], "...")
    

    # step 2:creating reader agent to read the search result and extract the relevant information from it.

    print("\n" + "=" * 50)
    print("Step 2: Reader Agent is scraping the top resources...")
    print("=" * 50)

    reader_agent = build_reader_agent()
    
    reader_result = reader_agent.invoke({
        "input": (
            f"Based on the following search result about the topic: {topic}\n"
            f"pick the most relevant url and scrape it for deeper results.\n\n"
            f"Search Result:\n{state['search_result']}" 
        )
    })

    # Executing the scraping tool automatically if the model calls it
    if reader_result.tool_calls:
        tool_call = reader_result.tool_calls[0]
        from tools import scrape_url
        state["scraped_content"] = scrape_url.invoke(tool_call["args"]["url"])
    else:
        state["scraped_content"] = reader_result.content

    print("\nScraped Content \n", state["scraped_content"][:800], "...")

    # till here we have created a pipeline that takes a topic as input and then uses the search agent to search the web for recent data about the topic. The search result is then passed to the reader agent which scrapes the most relevant URL from the search result and returns the clean text content from that URL. The final output of the pipeline is stored in the state dictionary with the key "scraped_content".

    # step 3:creating writer chain to write a detailed report based on the scraped content and the topic.

    print("\n" + "=" * 50)
    print("Step 3: Writer Chain is generating the report...")
    print("=" * 50)

    # now combining the search result and the scraped content to pass it to the writer chain to generate a detailed report.

    research_combined = (
        f"Search Result:\n{state['search_result']}\n\n"
        f"Scraped Content:\n{state['scraped_content']}"
    )

    # call the writer chain to generate the report based on the topic and the research gathered from the search result and the scraped content.
    state["report"] = writer_chain.invoke({
         "topics": topic,
         "research": research_combined
    })
    print("\n Final Report \n", state["report"])

    # step 4: creating critic chain to evaluate the report generated by the writer chain and suggest improvements.
    print("\n" + "=" * 50)
    print("Step 4: Critic Chain is evaluating the report...")
    print("=" * 50)

    state["feedback"] = critic_chain.invoke({
        "report": state["report"]
    })
    print("\n Feedback \n", state["feedback"])

    # finally returning the state dictionary which contains the final output of the pipeline.
    return state

# now final to call this function we can use the below code to run the pipeline and get the final output.
if __name__ == "__main__":
    topic = input("Enter the topic you want to research: ")
    run_research_pipeline(topic)